### ISSUE TITLE
afschk silently ignores a non-existent file

### ISSUE THREAD

**Issue by hoglet67** [SteveFosdick/AcornFsUtils#2]
afschk silently ignores a non-existant image file

This has tripped me up a few times.

**Comment by SteveFosdick** [comment]
Dave, I believe this is fixed in: https://github.com/SteveFosdick/AcornFsUtils/commit/d966ca199df419f8968910ab7cba33e6dc04587b#diff-fb53380842a3895f7a6bf070ffd369f9
